 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/deposits", type: :request do
  
  # Deposit. As you add validations to Deposit, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Deposit.create! valid_attributes
      get deposits_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      deposit = Deposit.create! valid_attributes
      get deposit_url(deposit)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_deposit_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      deposit = Deposit.create! valid_attributes
      get edit_deposit_url(deposit)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Deposit" do
        expect {
          post deposits_url, params: { deposit: valid_attributes }
        }.to change(Deposit, :count).by(1)
      end

      it "redirects to the created deposit" do
        post deposits_url, params: { deposit: valid_attributes }
        expect(response).to redirect_to(deposit_url(Deposit.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Deposit" do
        expect {
          post deposits_url, params: { deposit: invalid_attributes }
        }.to change(Deposit, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post deposits_url, params: { deposit: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested deposit" do
        deposit = Deposit.create! valid_attributes
        patch deposit_url(deposit), params: { deposit: new_attributes }
        deposit.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the deposit" do
        deposit = Deposit.create! valid_attributes
        patch deposit_url(deposit), params: { deposit: new_attributes }
        deposit.reload
        expect(response).to redirect_to(deposit_url(deposit))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        deposit = Deposit.create! valid_attributes
        patch deposit_url(deposit), params: { deposit: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested deposit" do
      deposit = Deposit.create! valid_attributes
      expect {
        delete deposit_url(deposit)
      }.to change(Deposit, :count).by(-1)
    end

    it "redirects to the deposits list" do
      deposit = Deposit.create! valid_attributes
      delete deposit_url(deposit)
      expect(response).to redirect_to(deposits_url)
    end
  end
end
