 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/transfers", type: :request do
  
  # Transfer. As you add validations to Transfer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Transfer.create! valid_attributes
      get transfers_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      transfer = Transfer.create! valid_attributes
      get transfer_url(transfer)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_transfer_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      transfer = Transfer.create! valid_attributes
      get edit_transfer_url(transfer)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Transfer" do
        expect {
          post transfers_url, params: { transfer: valid_attributes }
        }.to change(Transfer, :count).by(1)
      end

      it "redirects to the created transfer" do
        post transfers_url, params: { transfer: valid_attributes }
        expect(response).to redirect_to(transfer_url(Transfer.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Transfer" do
        expect {
          post transfers_url, params: { transfer: invalid_attributes }
        }.to change(Transfer, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post transfers_url, params: { transfer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested transfer" do
        transfer = Transfer.create! valid_attributes
        patch transfer_url(transfer), params: { transfer: new_attributes }
        transfer.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the transfer" do
        transfer = Transfer.create! valid_attributes
        patch transfer_url(transfer), params: { transfer: new_attributes }
        transfer.reload
        expect(response).to redirect_to(transfer_url(transfer))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        transfer = Transfer.create! valid_attributes
        patch transfer_url(transfer), params: { transfer: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested transfer" do
      transfer = Transfer.create! valid_attributes
      expect {
        delete transfer_url(transfer)
      }.to change(Transfer, :count).by(-1)
    end

    it "redirects to the transfers list" do
      transfer = Transfer.create! valid_attributes
      delete transfer_url(transfer)
      expect(response).to redirect_to(transfers_url)
    end
  end
end
