 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/withdraws", type: :request do
  
  # Withdraw. As you add validations to Withdraw, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Withdraw.create! valid_attributes
      get withdraws_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      withdraw = Withdraw.create! valid_attributes
      get withdraw_url(withdraw)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_withdraw_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      withdraw = Withdraw.create! valid_attributes
      get edit_withdraw_url(withdraw)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Withdraw" do
        expect {
          post withdraws_url, params: { withdraw: valid_attributes }
        }.to change(Withdraw, :count).by(1)
      end

      it "redirects to the created withdraw" do
        post withdraws_url, params: { withdraw: valid_attributes }
        expect(response).to redirect_to(withdraw_url(Withdraw.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Withdraw" do
        expect {
          post withdraws_url, params: { withdraw: invalid_attributes }
        }.to change(Withdraw, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post withdraws_url, params: { withdraw: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested withdraw" do
        withdraw = Withdraw.create! valid_attributes
        patch withdraw_url(withdraw), params: { withdraw: new_attributes }
        withdraw.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the withdraw" do
        withdraw = Withdraw.create! valid_attributes
        patch withdraw_url(withdraw), params: { withdraw: new_attributes }
        withdraw.reload
        expect(response).to redirect_to(withdraw_url(withdraw))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        withdraw = Withdraw.create! valid_attributes
        patch withdraw_url(withdraw), params: { withdraw: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested withdraw" do
      withdraw = Withdraw.create! valid_attributes
      expect {
        delete withdraw_url(withdraw)
      }.to change(Withdraw, :count).by(-1)
    end

    it "redirects to the withdraws list" do
      withdraw = Withdraw.create! valid_attributes
      delete withdraw_url(withdraw)
      expect(response).to redirect_to(withdraws_url)
    end
  end
end
